version: '3'
      
networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    restart: unless-stopped
    networks:
      - kommonitor
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak-data
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
  keycloak:
    volumes:
      - ../certs:/opt/keycloak/demo/certs
      - ./realms/prod/realm-export-kommonitor.json:/opt/keycloak/data/import/realm.json
    command:
      - start
      - --import-realm
    ports:
      - 8443:8443
    depends_on:
      - keycloak-db
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak-data
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_SCHEMA=public
      - KC_HOSTNAME=keycloak
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/demo/certs/cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/demo/certs/key.pem
      - KC_SPI_CONNECTIONS_JPA_LEGACY_MIGRATION_STRATEGY=update
      # - KC_HOSTNAME_ADMIN=keycloak
      # - KC_HTTP_ENABLED=true
      # - KC_HOSTNAME_STRICT=true
      # - KC_HOSTNAME_STRICT_HTTPS=true
      # - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/demo/certs/keycloakcert.pem
      # - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/demo/certs/keycloakkey.pem